apiVersion: v1
kind: Pod
metadata:
  name: mysite
  labels:
    app: mysite
spec:
  containers:
  - name: mysite
    image: ghcr.io/stevenoll/cis-92:main
    imagePullPolicy: Always
    livenessProbe:
      httpGet:
        path: /polls/
        port: 8000
    resources:
      limits:
        cpu: 250m 
        memory: 512Mi
        ephemeral-storage: 10Mi    
    ports:
    - containerPort: 8000
    env:
    - name: DB_ENGINE
      value: "sqlite"
    - name: DJANGO_ADMIN_EMAIL
      value: "test@test.test"
    - name: DJANGO_ADMIN_USERNAME
      value: "test"
    - name: DJANGO_SUPERUSER_PASSWORD
      value: "test"